apiVersion: v1
kind: Service
metadata:
  name: expensetracker-service
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
