apiVersion: v1
kind: Service
metadata:
  name: expensetracker-service
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080  # Updated to match containerPort in deployment
  type: NodePort
