apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensetracker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: expensetracker-container
          image: javatechie/expense-tracker:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"