# CI/CD pipeline for expense-tracker using GitHub Actions
# Builds the Java project, creates a Docker image, and deploys to Minikube

name: expense-tracker-cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: main

      # Step 2: Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Build and push Docker image
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: javatechie/expense-tracker
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Check out the code again for deploy
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: main  # Ensure correct branch

      # Step 2: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      # Step 3: Set up Minikube (Local)
      - name: Set up Minikube (Local)
        run: |
          minikube start --driver=docker
          kubectl config use-context minikube

      # Step 4: Apply Kubernetes Deployment and Service
      - name: Apply Kubernetes Deployment and Service
        run: |
          kubectl apply -f ./k8s-deployment.yaml --validate=false
          kubectl apply -f ./k8s-service.yaml --validate=false

      # Step 5: Debug Minikube and Kubernetes Resources
      - name: Debug Minikube and Kubernetes Resources
        run: |
          # Get the list of pods to check if any are running
          kubectl get pods

          # Get detailed information about the pods
          kubectl get pods -o wide
          
          # Describe the deployment to find any issues with pods or containers
          kubectl describe deployment expensetracker-deployment
          
          # Describe the pod(s) based on label selector to find out more details
          kubectl describe pod -l app=spring-boot-k8s
          
          # View logs of the pod(s) to troubleshoot issues
          kubectl logs -l app=spring-boot-k8s

          # Get the minikube logs for more information
          minikube logs --file=minikube-logs.txt

      # Step 6: Expose application (optional)
      - name: Expose application (optional)
        run: |
          minikube service expensetracker-service --url || echo "Service not yet available"
