name: expense-tracker-cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: javatechie/expense-tracker
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Minikube (Local)
        run: |
          minikube start --driver=docker --cpus=2 --memory=4g
          eval $(minikube -p minikube docker-env)
          kubectl config use-context minikube

      - name: Apply Kubernetes Deployment and Service
        run: |
          kubectl apply -f ./k8s-deployment.yaml --validate=false
          kubectl apply -f ./k8s-service.yaml --validate=false

      - name: Wait for pods to be running
        run: |
          kubectl rollout status deployment/expensetracker-deployment --timeout=300s
          kubectl get pods
          kubectl get pods -o wide

      - name: Debug Minikube and Kubernetes Resources
        run: |
          kubectl describe deployment expensetracker-deployment
          kubectl describe pod -l app=spring-boot-k8s
          kubectl logs -l app=spring-boot-k8s
          minikube logs --file=minikube-logs.txt

      - name: Wait for service to be available
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/expensetracker-deployment
          minikube service expensetracker-service --url || echo "Service not yet available"
